version: '3'
volumes:
  node_modules:

services:
  connect_bi_reporter_dev:
    container_name: connect_bi_reporter_dev
    build:
      context: .
    working_dir: /extension
    command: cextrun -d --no-rich-logging
    volumes: 
      - .:/extension
      - node_modules:/extension/node_modules
    env_file:
      - .connect_bi_reporter_dev.env
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:1q2w3e@db/bi_reporter
    depends_on:
      - db

  connect_bi_reporter_bash:
    container_name: connect_bi_reporter_bash
    build:
      context: .
    working_dir: /extension
    command: /bin/bash
    stdin_open: true
    tty: true
    volumes:
      - .:/extension
      - node_modules:/extension/node_modules
    env_file:
      - .connect_bi_reporter_dev.env
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:1q2w3e@db/bi_reporter
    depends_on:
      - db
    links:
      - "db_ram:db"

  connect_bi_reporter_test:
    container_name: connect_bi_reporter_test
    build:
      context: .
    working_dir: /extension
    command: extension-test
    volumes:
      - .:/extension
      - node_modules:/extension/node_modules
    env_file:
      - .connect_bi_reporter_dev.env
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:1q2w3e@db/bi_reporter
    depends_on:
      - db
    links:
      - "db_ram:db"

  db:
    image: postgres:9.6-alpine
    restart: always
    ports:
      - '5433:5432'
    expose:
      - '5432'
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 1q2w3e
      POSTGRES_DB: bi_reporter

  db_ram:
    image: postgres:9.6-alpine
    tmpfs:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 1q2w3e
      POSTGRES_DB: bi_reporter
