name: Test Connect BI Reporter

on:
  push:
    branches: '*'
    tags:
        - '*'
  pull_request:
    branches: [ master ]

jobs:
  backend:
    runs-on: ubuntu-latest
    name: Backend tests
    strategy:
      matrix:
        python-version: ['3.10']
        database-name:
          - bi_reporter
        database-password:
          - 1q2w3e
    services:
      db:
        image: postgres:11.5
        env:
          POSTGRES_PASSWORD: ${{ matrix.database-password }}
          POSTGRES_DB: ${{ matrix.database-name }}
        ports:
        - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false --local
          poetry install --no-root
      - name: Linting
        run: |
          flake8 .
      - name: Testing
        run: |
          DATABASE_URL=postgresql+psycopg2://postgres:${{ matrix.database-password }}@localhost:5432/${{ matrix.database-name }} pytest

  frontend:
    runs-on: ubuntu-latest
    name: Frontend tests
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Linting
        run: npm run lint
      - name: Check formatting
        run: npm run format:check
      - name: Testing
        run: npm run test
